### ISSUE TITLE
Episodic blindness

### ISSUE THREAD

**Issue by saizai** [bemyeyes/bemyeyes-server#12]
Does the app support a user being in both blind and sighted roles?

E.g. I have an episodic functional blindness due to extreme light sensitivity. In some situations, I'm effectively 100% blind; in most I'm more or less normally sighted. It would be good to be able to have both roles available to me.

**Comment by khebbie** [comment]
I assume this is a bit of a special case, I will take it back to the team and discuss.

**Comment by Thelle** [comment]
Thank you for feedback @saizai - really appreciate it! I can see that it makes sense in your specific case - and you are able to have one email on which you log in as blind and one where you log in as sighted.. We don't want it to be easy to switch from sighted to blind since we already now experience false calls.

**Comment by saizai** [comment]
Will check it out once you have an android version up. ;-)

Though my situation's a bit unusual, 'blind' is not binary either. E.g.
someone with tunnel vision but relatively normal acuity could potentially
answer questions on the app for someone with other forms of blindness.

I think that it would be empowering to allow blind people who have partial
sight to participate in helping others.

Similarly, they could help hear things for deaf people (if they can sign
well), and deaf people can help see things for blind people (if they can
speak well).

I'd suggest that the implicit helper/helpee dichotomy is socially
restrictive and implies a onesidedness that, while well intentioned, is
implicitly condescending.

FWIW as one case in point: one of my best experiences in seamless
communication when it'd otherwise be seriously impaired was, while I was
mute, a friend of mine who's an ASL interpreting student (and blind) was
touch-reading my signing.

Something to consider. ;-)

**Comment by Thelle** [comment]
Thank you for your additional feedback - we realize this - the inventor of Be My Eyes, , Hans Jørgen Wiberg, has RP (tunnelvision) himself and has helped multiple times. Furthermore we know of other  users who have 'partial sight' who have helped already in the Be My Eyes network as "sighted helpers" - we think this is wonderful. For now you'll have to use two different login's - and logging out of one account and into another is really quick - even more so if one of them are with facebook login (one touch of a button) :)
