### ISSUE TITLE
Add text-based response

### ISSUE THREAD

**Issue by saizai** [bemyeyes/bemyeyes-server#13]
Some helpers may be able to respond using text but not speech (e.g. if deaf, mute, in a noisy environment, etc).

Please add a way for helpers to respond using text that is displayed in large type and spoken by text-to-speech for the recipient.

**Comment by khebbie** [comment]
This is not in the plan for Be My Eyes

**Comment by billierain** [comment]
it's the right thing to do. and if cost is an issue, there are grants out there that provide funding for these kinds of access projects. these kinds of services mean so much in the lives of people with disabilities. I hope you decide to make it everything it can be.
