### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by hairychris** [bemyeyes/bemyeyes-server#8]
Hey BeMyEyes Team,

Firstly, an excellent idea, great work and thank you.

I read on the FAQ on your site the following:

"We would love to, but right now it is not possible, because the system we use can only handle video between iPhones. But we know that there are a lot of potential users with Android and Windows phones out there."

What system are you guys using to send video? Is it peer to peer or is it client server? Could this be switched out to something like WebRTC? I know that in order to get round NAT restrictions we would need to use STUN (and potentially TURN) servers but it could save on server costs. It is also cross platform right from a web browser or a phone. 

Support within mobile web browsers is currently poor but improving all the time. It would be extremely surprising if it is not adopted right across the board. It can clearly be used in iOS (just in an app and not within Safari) as someone has released a browser that supports it: http://www.openwebrtc.io/bowser/

It is supported natively under Android, instructions are here: http://www.webrtc.org/native-code/android

Do you think this is a potential solution to the cross-platform issue or would this be far too much work? I'm willing to help out, I'm a Python developer by trade, I noticed you are using Ruby on the server but it doesn't seem like anything too complex is going on server side. I have zero experience with iOS application and some limited experience with Android.

One thing that would be worth thinking about as well is hybrid mobile applications using something like http://phonegap.com/

Hope this wasn't too long.

Chris

**Comment by Thelle** [comment]
The FAQ was written at a time when webRTC in OpenTok was only in beta - it is now supported and I have updated the FAQ.

**Comment by hairychris** [comment]
Ah great it's already using WebRTC, brilliant. One more question, what is the status of an Android port?

**Comment by Thelle** [comment]
There are two guys who have started working on a version, but will not be on Be My Eyes' GitHub till it has matured a bit..
